title: Yuxuan Yuan (原宇轩)
description: The journey continues. 
baseurl: "" # Leave empty if your site is at the root of your domain
url: "https://yyx319.github.io" # Replace with your GitHub Pages URL

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Optional settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Custom navigation links
navigation:
  - title: "Education"
    url: /education/
  - title: "Astrophysics Research"
    url: /astrophysics-research/
